// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdOjQGxxjgRjUbwjdOfwQBWHCUM774_KM',
    appId: '1:397371503908:web:cc7073671dc5bcc48cafb1',
    messagingSenderId: '397371503908',
    projectId: 'fir-flutter-codelab-a9f90',
    authDomain: 'fir-flutter-codelab-a9f90.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a9f90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALLFmFFo9JSjXhMgY9BOA6wQznVT6ftAc',
    appId: '1:397371503908:android:a5ddd0dbf729a77f8cafb1',
    messagingSenderId: '397371503908',
    projectId: 'fir-flutter-codelab-a9f90',
    storageBucket: 'fir-flutter-codelab-a9f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshcw4bbpS_vDwg7ATd1CILs8Y0G_wXUY',
    appId: '1:397371503908:ios:b158c10d27b388f28cafb1',
    messagingSenderId: '397371503908',
    projectId: 'fir-flutter-codelab-a9f90',
    storageBucket: 'fir-flutter-codelab-a9f90.appspot.com',
    iosClientId: '397371503908-c7d70drav8r6sbe8c1tockg59ath1ir5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBshcw4bbpS_vDwg7ATd1CILs8Y0G_wXUY',
    appId: '1:397371503908:ios:b158c10d27b388f28cafb1',
    messagingSenderId: '397371503908',
    projectId: 'fir-flutter-codelab-a9f90',
    storageBucket: 'fir-flutter-codelab-a9f90.appspot.com',
    iosClientId: '397371503908-c7d70drav8r6sbe8c1tockg59ath1ir5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
